// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCexTI7aH5zEiRS4exNPa_audoK8NreNyw',
    appId: '1:842890999105:web:ac138c443d09a7c1e39dc0',
    messagingSenderId: '842890999105',
    projectId: 'pulse-app-41552',
    authDomain: 'pulse-app-41552.firebaseapp.com',
    storageBucket: 'pulse-app-41552.firebasestorage.app',
    measurementId: 'G-T96HJC8JWZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqhw8VKv4Nrbwuj8UwAvW-BlTlZpG4mcA',
    appId: '1:842890999105:android:5ce204f62ca58bf6e39dc0',
    messagingSenderId: '842890999105',
    projectId: 'pulse-app-41552',
    storageBucket: 'pulse-app-41552.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsBEZqKMi9Dgk1F_D5ya_HlrjBDq6UdSw',
    appId: '1:842890999105:ios:dc3058048ad08f83e39dc0',
    messagingSenderId: '842890999105',
    projectId: 'pulse-app-41552',
    storageBucket: 'pulse-app-41552.firebasestorage.app',
    iosBundleId: 'com.example.plusApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsBEZqKMi9Dgk1F_D5ya_HlrjBDq6UdSw',
    appId: '1:842890999105:ios:dc3058048ad08f83e39dc0',
    messagingSenderId: '842890999105',
    projectId: 'pulse-app-41552',
    storageBucket: 'pulse-app-41552.firebasestorage.app',
    iosBundleId: 'com.example.plusApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCexTI7aH5zEiRS4exNPa_audoK8NreNyw',
    appId: '1:842890999105:web:a89790a1176b402be39dc0',
    messagingSenderId: '842890999105',
    projectId: 'pulse-app-41552',
    authDomain: 'pulse-app-41552.firebaseapp.com',
    storageBucket: 'pulse-app-41552.firebasestorage.app',
    measurementId: 'G-K69XXLM863',
  );
}
